import NavBar from "@/components/shared/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Template from "./template";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Gadget Galaxy",
	description: "Generated by create next app",
	icons: "/logo.png",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning className="overflow-x-hidden">
			<ClerkProvider>
				<body className={inter.className}>
					<ToastContainer
						position="top-right"
						stacked
						autoClose={5000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme="light"
					/>
					<NavBar />
					<Template>{children}</Template>
					<Footer />
				</body>
			</ClerkProvider>
		</html>
	);
}
